/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8faf8",
        "surface-tint": "#006e1c",
        "secondary-fixed-dim": "#ffb870",
        "on-tertiary-fixed-variant": "#00497d",
        "surface-dim": "#d8dad9",
        "surface-variant": "#e1e3e1",
        "primary-fixed-dim": "#78dc77",
        "on-secondary": "#ffffff",
        "outline-variant": "#becab9",
        "inverse-on-surface": "#eff1ef",
        "primary": "#006e1c",
        "surface": "#f8faf8",
        "primary-container": "#4caf50",
        "surface-container": "#eceeec",
        "primary-fixed": "#94f990",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "tertiary-container": "#33a0fe",
        "background": "#f8faf8",
        "on-surface": "#191c1b",
        "outline": "#6f7a6b",
        "inverse-primary": "#78dc77",
        "surface-container-low": "#f2f4f2",
        "on-primary-fixed": "#002204",
        "secondary": "#8b5000",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#2c1600",
        "on-secondary-container": "#653900",
        "tertiary-fixed-dim": "#9ecaff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3130",
        "on-background": "#191c1b",
        "tertiary": "#0061a4",
        "on-secondary-fixed-variant": "#693c00",
        "on-primary": "#ffffff",
        "on-primary-container": "#003c0b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdcbe",
        "secondary-container": "#ff9800",
        "surface-container-high": "#e6e9e7",
        "on-surface-variant": "#3f4a3c",
        "on-primary-fixed-variant": "#005313",
        "on-tertiary-container": "#00355d",
        "on-tertiary-fixed": "#001d36",
        "tertiary-fixed": "#d1e4ff",
        "surface-container-highest": "#e1e3e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "telugu-body": ["Inter"]
      }
    },
  },
  plugins: [],
}
